### ISSUE TITLE
Call for testing /dev before 0.7.4 beta

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#575]
I would like to release the 0.7.4 in the next few days (saturday / sunday / next week-end?).

But before, there are some tickets I want to close:
- [x] #399 (HTML5 notifications) is nearly finished! It works fine for me ;)
- [x] #430 (hide feeds with no unread articles) is still missing an option but it should be done  quickly
- [x] #494 (bug in import / export) is in an unknown state but I have worked on it last night. It is better at least!
- [x] #495 (bug of main stream without any articles -> bug with ordering?) is the more complicated bug I think but it could be great to fix it quickly :)
- [x] #539 (dynamic favicon) is nearly finished too.
- [x] #574 (cannot create new users with SQLite) is critical but should be quite easy to fix.

That's all for me! If you have another ideas of things we should finish before next release, feel free to add them in comments.

Obviously, we need to test, test and test before the final release.

Now, a word about version 0.8.0: it could be great to release it next month. I'm quite tired of branch 0.7.x and we have a LOT of new AWESOME features we could release in the stable version. Moreover, I finish my work at school / enterprise 14th september and begin my 6 months break: it means I will be able to work full time on FreshRSS! So more features, quicker and more tests! It also means I hope to release version 1.0 before the new year :) So I would like to finish branch 0.8.x at the same time of my enterprise contract so I could start new version with a lot of free time.
