### ISSUE TITLE
[Meta-ticket] New category systems

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#646]
Here I list all tickets relative to changes about category systems:
- [x] Transformer les badges « x non lus » en liens vers la vue « non lu » #148 
- [x] Permettre la réorganisation des catégories #190 
- [x] Modifier comportement des catégories (dépliement) #194 
- [x] [feature] catégories arborescentes ? #229 
- [x] Ajouter la hiérarchie à la gestion des abonnements #412 
- [x] Changer la catégorie de plusieurs flux #468

**Comment by marienfressinaud** [comment]
I closed all the related tickets that were still opened. I don't think we'll work soon on this and the actual system is quite good even if we still can improve the category system.

Let's close this too old ticket :)
