### ISSUE TITLE
[Meta-ticket] Release of version 1.0

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#733]
As I noticed @Alkarex and @aledeg by email, I want to release the version 1.0 of FreshRSS as soon as possible. At last! However, there still a lot of opened tickets and _I don't plan to close all of them before 1.0_.

This ticket is here to keep track of really wanted features (for me).
- [x] #252 Extension system (work in progress) (need #730)
- [x] #290 Not depend on an external service for favicons
- [x] #697 Cannot scroll a long category list (need #252)
- [x] #700 GET connection is not working
- [x] #729 Moving user data
- [x] #730 Improve configuration system
- [x] #731 Give possibility to extend i18n for extensions
- [x] #758 Unable to import TT-RSS Feeds via OPML
- [x] #760 Missing favicons after upgrading from 0.8.1 to 0.9.4
- [x] #761 Unable to login after upgrading from 0.9.3 to 0.9.4

Facultative:
- [ ] #763 FreshRSS constructor/init should allow multiple instances / changing user

We can discuss here of the priority of the different tickets (not listed too).

**Comment by marienfressinaud** [comment]
I have moved #732 after the 1.0. It is maybe not critical for now and it is a really big work.

**Comment by marienfressinaud** [comment]
I think it's ok to release the 0.9.4 now. Next step will be in two weeks with the 1.0 and I would like to avoid big changes now (such as refactoring). The 1.0 should be quite identical to the 0.9.4, just a bit more stabilized :).

**Comment by marienfressinaud** [comment]
Update script didn't work for me (it seems to be a right access problem but not sure where it happened). Next time I will test update scripts directly on the server. Update is not accessible while the bug is not fixed.

**Comment by marienfressinaud** [comment]
Ok, strange case: `./data/config.php` was not writable by the server. I added a test to make it writable if it's not. Update system should work now (I hope so! :s)

**Comment by Vincent14** [comment]
Hello, I tried it and it works perfectly :) Good job :)

**Comment by marienfressinaud** [comment]
Hop https://github.com/FreshRSS/FreshRSS/releases/tag/1.0.0 !
And hop https://github.com/FreshRSS/FreshRSS/releases/tag/1.1.0 !
And re-hop https://marienfressinaud.fr/index.php?article156/freshrss-un-point-zero (in French)!

I hope there is no more bugs :)
